# Site settings
title: Ingrijire batrani Anglia | Joburi de la 400£ pe saptamana fara comision. 
description: "Recrutam persoane pentru locuri de munca in industria ingrijirii batranilor in Marea Britanie. Nu percepem comision!"
baseurl:  # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: img/logo.jpg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Ingrijire batrani Anglia 
    hero_description: Joburi de la 400£ pe saptamana FARA COMISION
    hero_warning: Datorita nevoilor angajatorului candidatii femei au cele mai multe sanse de a primi un loc de munca.


# Contact form
api_token: 3cac6c542f9505efdf4552fd1330b683

# Contact info
contact:
    name: Liliana Alexandru
    phone: +44 7817 441126
    email: caregiveruk@gmail.com
    address: 29 Parnell Avenue, Lichfield, Staffordshire, WS13 6NX, United Kingdom
    skype: caregiveruk.recruitment

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Von schroeders 273, Viña del mar, Chile
    address_details: svg/min/logo.svg

# Social settings
email: mailto:caregiveruk@gmail.com
whatsapp: whatsapp://send?text=Hello
facebook: http://facebook.com/caregiver.ro
skype: skype:caregiveruk.recruitment?userinfo
feed: yes

# Footer
copyright: © 2015 CareGiver - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: UA-72814372-1
google_verification:
